# Generated by Django 3.0.7 on 2020-06-13 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jurnal', '0002_reference_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='tags',
        ),
    ]
